GET http://127.0.0.1:5000/

###

GET http://127.0.0.1:5000/data/Juan

###

GET http://127.0.0.1:5000/user

###

POST http://127.0.0.1:5000/user
Content-Type: application/json

{
  "name": "juan",
  "username": 1,
  "email": "juan",
  "password": "1234"
}

###

GET http://127.0.0.1:5000/user_test

###

GET http://127.0.0.1:5000/user_test/1

###

POST http://127.0.0.1:5000/user_test
Content-Type: application/json

{
  "name": "juan",
  "username": "juan123",
  "email": "juan@example.com",
  "password": "1234"
}

###

POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "username": "juan123",
  "password": "1234"
}

###

GET http://127.0.0.1:5000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MjE4NjQyMTV9.3OH_Z55daIdp8igdKX_CsnTSCgE0-NSBXsOTEboIz5E

